version: '3'

services:
    database-manager:
        image: mysql/mysql-cluster
        networks:
            database_net:
                ipv4_address: 172.50.0.2
        command: ndb_mgmd --ndb-nodeid=2
        ports:
            - "1186:1186"
        volumes:
            - "./cnf/my.cnf:/etc/my.cnf"
            - "./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf"

    node:
        image: mysql/mysql-cluster
        command: ndbd 
        networks:
            - database_net
        depends_on:
            - database-manager
        volumes:
            - "./cnf/my.cnf:/etc/my.cnf"
            - "./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf"

    database-server:
        image: mysql/mysql-cluster
        networks:
            database_net:
                ipv4_address: 172.50.0.3
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_DATABASE=my_db
            - MYSQL_USER=my_user
            - MYSQL_ROOT_PASSWORD: root_toor
            - MYSQL_ROOT_HOST=%
        ports:
            - "3307:3306"
        command: mysqld --ndb-nodeid=3
        volumes:
            - "./cnf/my.cnf:/etc/my.cnf"
            - "./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf"


networks:
    database_net:
        ipam:
            config:
                - subnet: 172.50.0.0/16